### ISSUE TITLE
Error, any Idea about this Failor

### ISSUE THREAD

**Issue by Roughtrade** [eprst/pimpd#1]
python pimpd.py 
Traceback (most recent call last):
  File "pimpd.py", line 37, in <module>
    mpd_client = reconnectingclient.ReconnectingClient()
  File "/home/pi/pimpd/pimpd/reconnectingclient.py", line 11, in __init__
    super(ReconnectingClient, self).__init__(use_unicode=True)
TypeError: __init__() got an unexpected keyword argument 'use_unicode'

Regards Peter

**Comment by eprst** [comment]
Hi
please double check that you've got `python-mpd2`, not `python-mpd` installed.

**Comment by Roughtrade** [comment]
Thank You !!!!
Regards Peter
